### PR TITLE
add more subscripts and superscripts

### PR DESCRIPTION
**Pull request by ddrake**
Hi -- this is a very useful project for me -- thanks!

This pull request is to add more subscripts and superscripts from 
https://bitbucket.org/mortiferus/latex-pretty-symbols.el/src/default/

Unfortunately it seems we are still limited in the subscripts available.

Best,
Dow

### CODE REVIEW

**Comment by ddrake** [comment]
Adding some useful subscripts from [here](https://stackoverflow.com/questions/17908593/how-to-find-the-unicode-of-the-subscript-alphabet):

**Comment by martinsifrar** [comment]
I was about to add those sub/superscripts myself and then I noticed this. @joom Is there any way this could be merged? Pretty please?

**Comment by martinsifrar** [comment]
I was about to add those sub/superscripts myself and then I noticed this. @joom Is there any way this could be merged?

**Comment by joom** [comment]
Thanks! Sorry about the delay.

**Pull request merged**
